[package]
name = "RustyCOV"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["cargo"] }
walkdir = "2.5.0"
ureq = { version = "3.1.2", features = ["gzip", "rustls"] }
indicatif = { version = "0.18.0", default-features = false }
thiserror = "2.0.17"

[target.'cfg(windows)'.dependencies]
zip = { version = "6.0.0", default-features = false, features = ["deflate"] }
windows-sys = { version = "0.61.2", default-features = false, features = [
    "Win32_System_Threading", "Win32_System_Console",
] }

[target.'cfg(unix)'.dependencies]
xz2 = { version = "0.1.7", default-features = false, features = ["static"] }
tar = { version = "0.4.44", default-features = false }
