edition = "2024"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Module"
imports_layout = "Horizontal"
group_imports = "StdExternalCrate"
wrap_comments = true
binop_separator = "Back"
brace_style = "PreferSameLine"
combine_control_expr = false
control_brace_style = "AlwaysSameLine"
use_small_heuristics = "Max"
max_width = 100
