[package]
name = "rusty_cov_cli"
version = "0.1.0"
description = "Command-line interface for the RustyCOV tool"
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rusty_cov = { path = "../lib", default-features = false }
clap = { version = "4.5.50", features = ["cargo"] }

[features]
default = ["png-opt", "jpeg-opt"]

png-opt = ["rusty_cov/png-opt"]
jpeg-opt = ["rusty_cov/jpeg-opt"]
